# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-11 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Getaddr',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(null=True)),
                ('fulladdr', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('etc', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'getaddr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('safeqnum', models.IntegerField(blank=True, null=True)),
                ('answer', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
