# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-12 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0002_orderform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='getaddr',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderform',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
