# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-14 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0004_user_portrait'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('number', models.IntegerField()),
                ('time', models.DateField()),
            ],
            options={
                'db_table': 'shopping',
            },
        ),
        migrations.RenameField(
            model_name='orderform',
            old_name='pcid',
            new_name='pid',
        ),
        migrations.AddField(
            model_name='getaddr',
            name='street',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='getaddr',
            name='username',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='getaddr',
            name='uid',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='ordernumber',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
