# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-20 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0005_auto_20190814_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('pcid', models.IntegerField()),
                ('mername', models.CharField(max_length=45)),
                ('money', models.FloatField()),
                ('color', models.CharField(max_length=128, null=True)),
                ('specification', models.CharField(max_length=128, null=True)),
                ('size', models.CharField(max_length=128, null=True)),
                ('capacity', models.CharField(max_length=128, null=True)),
                ('xiaoliang', models.IntegerField(null=True)),
                ('kucun', models.IntegerField(default=10)),
                ('show', models.IntegerField()),
                ('inf', models.CharField(max_length=45)),
                ('picture', models.CharField(blank=True, max_length=255, null=True)),
                ('Choosepicture', models.CharField(max_length=255, null=True)),
                ('infpicture', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'merchandise',
                'managed': False,
            },
        ),
        migrations.RenameField(
            model_name='shopping',
            old_name='number',
            new_name='mid',
        ),
        migrations.RenameField(
            model_name='shopping',
            old_name='pid',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='time',
        ),
        migrations.AddField(
            model_name='shopping',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopping',
            name='picture',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='shopping',
            table='shopcar',
        ),
    ]
