"""
Django settings for django_chuizi project.

Generated by 'django-admin startproject' using Django 1.11.16.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4(egq1f&c&7_rt8rtwi9xj8h2716mcz4(%-i2h4m)j(ta$3e)='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'App',
    'operate',
    'smartisan_manage',
    'rest_framework'
]


PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_chuizi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_chuizi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "smartisan",
        "HOST":"49.232.41.35",
        "USER":"root",
        "PASSWORD":"0328",
        "POST":"3306"
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# 设置session过期时间
MAXAGE = 1 * 24 * 3600
MAXAGECODE = 5 * 60
SALTVALUE = '9a15ae9f'

# 设置图片上传路径
MDEIA_ROOT = os.path.join(BASE_DIR,'static/usrpic/')

# smtp服务的邮箱服务器器
EMAIL_HOST = 'smtp.126.com'
# smtp服务固定的端口口是25
EMAIL_PORT = 25
#发送邮件的邮箱
EMAIL_HOST_USER = 'cn1yzz@126.com'
#在邮箱中设置的客户端授权密码
EMAIL_HOST_PASSWORD = 'zhangzy0328'
#收件人人看到的发件人 <此处要和发送邮件的邮箱相同>
EMAIL_FROM = 'hello<cn1yzz@126.com>'



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR,"static")]


SMSCONFIG = {
    'ACCESS_KEY_ID':'LTAIyGMFRE9VwmFu',
    'ACCESS_KEY_SECRET':'AmLvtafscQ2PuMxeK4KxdCDieB2mMV',
    'SignName':'djangoenv',
    'TemplateCode':'SMS_172205983',
}

# 支付宝支付
APP_PRIVATE_KEY = open(os.path.join(BASE_DIR,'alipay/app_private_key.pem')).read()
ALIPAY_PBULIC_KEY = open(os.path.join(BASE_DIR,'alipay/alipay_public_key.pem')).read()
ALI_APP_ID = '2016101200669379'
