# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-11 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aaa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
            ],
            options={
                'db_table': 'aa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Breath',
            fields=[
                ('idbreath', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('money', models.FloatField()),
                ('picture', models.CharField(blank=True, max_length=45, null=True)),
                ('infpicture', models.CharField(blank=True, max_length=45, null=True)),
                ('infserver', models.CharField(blank=True, max_length=45, null=True)),
                ('inf', models.CharField(blank=True, max_length=45, null=True)),
                ('black', models.IntegerField()),
                ('white', models.IntegerField()),
                ('fuhe', models.IntegerField()),
                ('jiaquan', models.IntegerField()),
                ('biaozhun', models.IntegerField()),
                ('xiaoliang', models.IntegerField()),
                ('tochan', models.IntegerField()),
                ('kucun', models.IntegerField()),
            ],
            options={
                'db_table': 'breath',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('idclothes', models.AutoField(primary_key=True, serialize=False)),
                ('money', models.FloatField()),
                ('name', models.CharField(max_length=45)),
                ('picture', models.CharField(blank=True, max_length=45, null=True)),
                ('infpicture', models.CharField(blank=True, max_length=45, null=True)),
                ('inf', models.CharField(blank=True, max_length=45, null=True)),
                ('infserver', models.CharField(blank=True, max_length=45, null=True)),
                ('black', models.IntegerField()),
                ('white', models.IntegerField()),
                ('fifteen_6', models.IntegerField()),
                ('twenty', models.IntegerField()),
                ('notopen', models.IntegerField()),
                ('s', models.IntegerField()),
                ('l', models.IntegerField()),
                ('m', models.IntegerField()),
                ('xl', models.IntegerField()),
                ('man', models.IntegerField()),
                ('kid', models.IntegerField()),
                ('women', models.IntegerField()),
                ('three_7', models.IntegerField()),
                ('three_8', models.IntegerField()),
                ('three_9', models.IntegerField()),
                ('four_0', models.IntegerField()),
                ('four_1', models.IntegerField()),
                ('four_2', models.IntegerField()),
                ('xiaoliang', models.IntegerField()),
                ('tochan', models.IntegerField()),
                ('kucun', models.IntegerField()),
            ],
            options={
                'db_table': 'clothes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indexcopy',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('hid', models.IntegerField()),
                ('cname', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'indexcopy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indexhome',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('gname', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'indexhome',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indexproduct',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=45, unique=True)),
                ('cid', models.IntegerField()),
            ],
            options={
                'db_table': 'indexproduct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndexTab',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'index_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('partsid', models.AutoField(primary_key=True, serialize=False)),
                ('partsname', models.CharField(max_length=45, unique=True)),
                ('money', models.FloatField()),
                ('one', models.IntegerField()),
                ('two', models.IntegerField()),
                ('three', models.IntegerField()),
                ('white', models.IntegerField()),
                ('black', models.IntegerField()),
                ('diantongban', models.IntegerField(blank=True, null=True)),
                ('picture', models.CharField(blank=True, max_length=45, null=True)),
                ('infpicture', models.CharField(blank=True, max_length=45, null=True)),
                ('inf', models.CharField(blank=True, max_length=45, null=True)),
                ('infserver', models.CharField(blank=True, max_length=45, null=True)),
                ('xiaoliang', models.IntegerField()),
                ('tochan', models.IntegerField()),
                ('kucun', models.IntegerField()),
            ],
            options={
                'db_table': 'parts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('idphone', models.AutoField(primary_key=True, serialize=False)),
                ('phonename', models.CharField(max_length=45)),
                ('picture', models.CharField(blank=True, max_length=45, null=True)),
                ('infpicture', models.CharField(blank=True, max_length=45, null=True)),
                ('inf', models.CharField(max_length=45)),
                ('money', models.FloatField()),
                ('white', models.IntegerField()),
                ('black', models.IntegerField()),
                ('six_64', models.IntegerField()),
                ('six_128', models.IntegerField()),
                ('eight_128', models.IntegerField()),
                ('eight_512', models.IntegerField()),
                ('gailan', models.CharField(blank=True, max_length=45, null=True)),
                ('sheji', models.CharField(blank=True, max_length=45, null=True)),
                ('gongneng', models.CharField(blank=True, max_length=45, null=True)),
                ('xiaoliang', models.IntegerField()),
                ('tochan', models.IntegerField()),
                ('kucun', models.IntegerField()),
            ],
            options={
                'db_table': 'phone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productcategorie',
            fields=[
                ('pcid', models.AutoField(primary_key=True, serialize=False)),
                ('pcname', models.CharField(max_length=45, unique=True)),
                ('cid', models.IntegerField()),
                ('hid', models.IntegerField()),
                ('money', models.FloatField()),
                ('inf', models.CharField(max_length=45)),
                ('picture', models.CharField(max_length=255)),
                ('white', models.IntegerField()),
                ('black', models.IntegerField()),
            ],
            options={
                'db_table': 'productcategorie',
                'managed': False,
            },
        ),
    ]
