# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-20 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20190814_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('pcid', models.IntegerField()),
                ('mername', models.CharField(max_length=45)),
                ('money', models.FloatField()),
                ('color', models.CharField(max_length=128, null=True)),
                ('specification', models.CharField(max_length=128, null=True)),
                ('size', models.CharField(max_length=128, null=True)),
                ('capacity', models.CharField(max_length=128, null=True)),
                ('inftwo', models.CharField(max_length=128, null=True)),
                ('xiaoliang', models.IntegerField(null=True)),
                ('kucun', models.IntegerField(default=10)),
                ('show', models.IntegerField()),
                ('Service', models.CharField(max_length=200, null=True)),
                ('inf', models.CharField(max_length=45)),
                ('picture', models.CharField(blank=True, max_length=255, null=True)),
                ('Choosepicture', models.CharField(max_length=255, null=True)),
                ('infpicture', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'merchandise',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='productcategorie',
            options={'managed': False},
        ),
    ]
